presets
preset0
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $01 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $00 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $10 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $00 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,RUST8,DARK_ORANGE8,DARK_LAVENDER8 ; colorValuesOfSomeSort
        .BYTE ULTRAMARINE_BLUE8,DARK_BLUE8,OLIVE_GREEN8,DARK_GREEN8
        .BYTE $00,$00,$00,$00,$00,$00,$00,$00 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $5A ; unused1
        .BYTE $20 ; unused2
preset1
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $01 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $00 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $10 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $02 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,RUST8,DARK_ORANGE8,DARK_LAVENDER8 ; colorValuesOfSomeSort
        .BYTE ULTRAMARINE_BLUE8,DARK_BLUE8,OLIVE_GREEN8,DARK_GREEN8
        .BYTE $00,$03,$03,$03,$03,$03,$03,$03 ; oozeRates
        .BYTE $01,$10,$10,$10,$10,$10,$10,$10 ; oozeSteps
        .BYTE $0F,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $00 ; unused1
        .BYTE $53 ; unused2
preset2
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $02 ; speedBoostAdjust
        .BYTE $01 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $03 ; pulseSpeed
        .BYTE $02 ; currentPulseWidth
        .BYTE $10 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $06 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,RUST8,DARK_ORANGE8,DARK_LAVENDER8 ; colorValuesOfSomeSort
        .BYTE ULTRAMARINE_BLUE8,DARK_BLUE8,OLIVE_GREEN8,DARK_GREEN8
        .BYTE $00,$01,$01,$01,$01,$01,$01,$01 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $41 ; unused1
        .BYTE $BE ; unused2
preset3
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $06 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $00 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $10 ; smoothingDelay
        .BYTE $02 ; currentSymmetry
        .BYTE $01 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,DARK_ORANGE1,DARK_ORANGE2,DARK_ORANGE4 ; colorValuesOfSomeSort
        .BYTE DARK_ORANGE6,DARK_ORANGE8,DARK_ORANGE10,DARK_ORANGE12
        .BYTE $00,$00,$00,$00,$00,$00,$00,$00 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $20 ; unused1
        .BYTE $20 ; unused2
preset4
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $06 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $00 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $08 ; smoothingDelay
        .BYTE $04 ; currentSymmetry
        .BYTE $02 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,DARK_ORANGE1,DARK_ORANGE2,DARK_ORANGE4 ; colorValuesOfSomeSort
        .BYTE DARK_ORANGE6,DARK_ORANGE8,DARK_ORANGE10,DARK_ORANGE12
        .BYTE $00,$03,$03,$03,$03,$03,$03,$03 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $20 ; unused1
        .BYTE $43 ; unused2
preset5
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $01 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $00 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $10 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $05 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $04 ; stroboscopicsEnabled
        .BYTE $04 ; stroboFlashRate
        .BYTE BLACK15,RED_ORANGE0,RED_ORANGE2,RED_ORANGE8 ; colorValuesOfSomeSort
        .BYTE RED_ORANGE10,DARK_ORANGE12,DARK_ORANGE14,MEDIUM_BLUE15
        .BYTE $00,$00,$00,$00,$00,$00,$00,$00 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $41 ; unused1
        .BYTE $94 ; unused2
preset6
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $10 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $00 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $10 ; smoothingDelay
        .BYTE $04 ; currentSymmetry
        .BYTE $01 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,DARK_ORANGE1,DARK_ORANGE2,DARK_ORANGE4 ; colorValuesOfSomeSort
        .BYTE DARK_ORANGE6,DARK_ORANGE8,DARK_ORANGE10,DARK_ORANGE12
        .BYTE $00,$00,$00,$00,$00,$00,$00,$00 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $53 ; unused1
        .BYTE $41 ; unused2
preset7
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $10 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $02 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $10 ; smoothingDelay
        .BYTE $04 ; currentSymmetry
        .BYTE $01 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,ULTRAMARINE_BLUE0,ULTRAMARINE_BLUE2,ULTRAMARINE_BLUE4 ; colorValuesOfSomeSort
        .BYTE ULTRAMARINE_BLUE6,ULTRAMARINE_BLUE8,ULTRAMARINE_BLUE10,MEDIUM_BLUE0
        .BYTE $00,$00,$00,$00,$00,$00,$00,$00 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $53 ; unused1
        .BYTE $59 ; unused2
preset8
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $01 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $00 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $10 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $06 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,ULTRAMARINE_BLUE4,COBALT_BLUE6,COBALT_BLUE10 ; colorValuesOfSomeSort
        .BYTE MEDIUM_BLUE15,COBALT_BLUE5,DARK_BLUE1,DARK_BLUE17
        .BYTE $00,$00,$00,$00,$00,$00,$00,$00 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $4F ; unused1
        .BYTE $4F ; unused2
preset9
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $09 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $00 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $08 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $02 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,DARK_ORANGE1,DARK_ORANGE2,DARK_ORANGE4 ; colorValuesOfSomeSort
        .BYTE DARK_ORANGE6,DARK_ORANGE8,DARK_ORANGE10,DARK_ORANGE12
        .BYTE $00,$03,$03,$03,$03,$03,$03,$03 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $2D ; unused1
        .BYTE $57 ; unused2
preset10
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $0A ; currentPatternIndex
        .BYTE $03 ; verticalResolutionSPAC
        .BYTE $00 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $10 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $05 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,RUST2,RUST4,RUST6 ; colorValuesOfSomeSort
        .BYTE RED_ORANGE11,DARK_ORANGE8,MEDIUM_BLUE3,DARK_BLUE8
        .BYTE $00,$00,$00,$00,$00,$00,$00,$00 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $41 ; unused1
        .BYTE $C0 ; unused2
preset11
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $02 ; speedBoostAdjust
        .BYTE $09 ; currentPatternIndex
        .BYTE $02 ; verticalResolutionSPAC
        .BYTE $03 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $10 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $01 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,RUST8,DARK_ORANGE8,DARK_LAVENDER8 ; colorValuesOfSomeSort
        .BYTE ULTRAMARINE_BLUE8,DARK_BLUE8,OLIVE_GREEN8,DARK_GREEN8
        .BYTE $00,$00,$00,$00,$01,$00,$00,$00 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $43 ; unused1
        .BYTE $52 ; unused2
preset12
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $02 ; currentPatternIndex
        .BYTE $03 ; verticalResolutionSPAC
        .BYTE $00 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $10 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $00 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,RUST2,RUST4,RUST6 ; colorValuesOfSomeSort
        .BYTE RED_ORANGE11,DARK_ORANGE8,MEDIUM_BLUE3,DARK_BLUE8
        .BYTE $00,$00,$00,$00,$00,$00,$00,$00 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $4F ; unused1
        .BYTE $0B ; unused2
preset13
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $02 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $00 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $10 ; smoothingDelay
        .BYTE $04 ; currentSymmetry
        .BYTE $04 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,RUST2,RUST4,RUST6 ; colorValuesOfSomeSort
        .BYTE RED_ORANGE11,DARK_ORANGE8,MEDIUM_BLUE3,DARK_BLUE8
        .BYTE $00,$00,$00,$00,$00,$00,$00,$00 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $00 ; unused1
        .BYTE $00 ; unused2
preset14
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $11 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $00 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $10 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $03 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,OLIVE_GREEN4,OLIVE_GREEN6,OLIVE_GREEN8 ; colorValuesOfSomeSort
        .BYTE OLIVE_GREEN10,OLIVE_GREEN12,OLIVE_GREEN10,OLIVE_GREEN8
        .BYTE $00,$01,$01,$01,$01,$01,$01,$01 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $43 ; unused1
        .BYTE $09 ; unused2
preset15
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $11 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $00 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $10 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $06 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,OLIVE_GREEN4,OLIVE_GREEN6,OLIVE_GREEN8 ; colorValuesOfSomeSort
        .BYTE OLIVE_GREEN10,OLIVE_GREEN12,OLIVE_GREEN10,OLIVE_GREEN8
        .BYTE $00,$01,$01,$01,$01,$01,$01,$01 ; oozeRates
        .BYTE $01,$02,$02,$03,$03,$05,$05,$06 ; oozeSteps
        .BYTE $0F,$20,$20,$20,$20,$20,$20,$20 ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $53 ; unused1
        .BYTE $09 ; unused2
preset16
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $07 ; speedBoostAdjust
        .BYTE $15 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $06 ; pulseSpeed
        .BYTE $05 ; currentPulseWidth
        .BYTE $08 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $05 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,DARK_ORANGE13,RED0,RED4 ; colorValuesOfSomeSort
        .BYTE RED8,RED12,DARK_LAVENDER0,DARK_LAVENDER4
        .BYTE $03,$00,$00,$00,$00,$00,$00,$00 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $01 ; explosionMode
        .BYTE $01 ; unused1
        .BYTE $50 ; unused2
preset17
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $17 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $01 ; pulseSpeed
        .BYTE $05 ; currentPulseWidth
        .BYTE $10 ; smoothingDelay
        .BYTE $02 ; currentSymmetry
        .BYTE $06 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,DARK_ORANGE13,RED0,RED4 ; colorValuesOfSomeSort
        .BYTE RED8,RED12,DARK_LAVENDER0,DARK_LAVENDER4
        .BYTE $03,$00,$00,$00,$00,$00,$00,$00 ; oozeRates
        .BYTE $10,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $03 ; explosionMode
        .BYTE $4C ; unused1
        .BYTE $4F ; unused2
preset18
        .BYTE $02 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $0D ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $01 ; pulseSpeed
        .BYTE $02 ; currentPulseWidth
        .BYTE $10 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $02 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,ULTRAMARINE_BLUE0,ULTRAMARINE_BLUE2,ULTRAMARINE_BLUE4 ; colorValuesOfSomeSort
        .BYTE ULTRAMARINE_BLUE6,ULTRAMARINE_BLUE8,ULTRAMARINE_BLUE10,MEDIUM_BLUE0
        .BYTE $00,$00,$00,$00,$00,$00,$00,$02 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $80 ; unused1
        .BYTE $02 ; unused2
preset19
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $02 ; speedBoostAdjust
        .BYTE $07 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $03 ; pulseSpeed
        .BYTE $08 ; currentPulseWidth
        .BYTE $10 ; smoothingDelay
        .BYTE $02 ; currentSymmetry
        .BYTE $06 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,DARK_ORANGE1,DARK_ORANGE2,DARK_ORANGE4 ; colorValuesOfSomeSort
        .BYTE DARK_ORANGE6,DARK_ORANGE8,DARK_ORANGE10,DARK_ORANGE12
        .BYTE $00,$01,$01,$01,$01,$01,$01,$01 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $31 ; unused1
        .BYTE $0C ; unused2
preset20
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $06 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $00 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $10 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $01 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,RUST8,DARK_ORANGE8,DARK_LAVENDER8 ; colorValuesOfSomeSort
        .BYTE ULTRAMARINE_BLUE8,DARK_BLUE8,OLIVE_GREEN8,DARK_GREEN8
        .BYTE $00,$01,$01,$01,$01,$01,$01,$01 ; oozeRates
        .BYTE $01,$10,$10,$10,$10,$10,$10,$10 ; oozeSteps
        .BYTE $0F,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $00 ; unused1
        .BYTE $01 ; unused2
preset21
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $09 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $00 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $10 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $02 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,RUST8,DARK_ORANGE8,DARK_LAVENDER8 ; colorValuesOfSomeSort
        .BYTE ULTRAMARINE_BLUE8,DARK_BLUE8,OLIVE_GREEN8,DARK_GREEN8
        .BYTE $00,$01,$01,$01,$01,$01,$01,$01 ; oozeRates
        .BYTE $01,$10,$10,$10,$10,$10,$10,$10 ; oozeSteps
        .BYTE $0F,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $4D ; unused1
        .BYTE $32 ; unused2
preset22
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $01 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $00 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $08 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $03 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,BLACK2,BLACK14,BLACK4 ; colorValuesOfSomeSort
        .BYTE BLACK12,BLACK6,BLACK10,BLACK8
        .BYTE $00,$02,$02,$02,$02,$02,$02,$02 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $50 ; unused1
        .BYTE $0A ; unused2
preset23
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $09 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $00 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $08 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $05 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,DARK_ORANGE1,DARK_ORANGE2,DARK_ORANGE4 ; colorValuesOfSomeSort
        .BYTE DARK_ORANGE6,DARK_ORANGE8,DARK_ORANGE10,DARK_ORANGE12
        .BYTE $00,$03,$03,$03,$03,$03,$03,$03 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$12,$13,$14,$15,$16,$17,$18 ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $4F ; unused1
        .BYTE $55 ; unused2
preset24
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $0C ; speedBoostAdjust
        .BYTE $06 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $00 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $01 ; smoothingDelay
        .BYTE $02 ; currentSymmetry
        .BYTE $06 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,RUST8,DARK_ORANGE8,DARK_LAVENDER8 ; colorValuesOfSomeSort
        .BYTE ULTRAMARINE_BLUE8,DARK_BLUE8,OLIVE_GREEN8,DARK_GREEN8
        .BYTE $00,$01,$01,$01,$01,$01,$01,$01 ; oozeRates
        .BYTE $01,$10,$10,$10,$10,$10,$10,$10 ; oozeSteps
        .BYTE $0F,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $53 ; unused1
        .BYTE $0B ; unused2
preset25
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $0F ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $01 ; pulseSpeed
        .BYTE $05 ; currentPulseWidth
        .BYTE $08 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $02 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,DARK_ORANGE13,RED0,RED4 ; colorValuesOfSomeSort
        .BYTE RED8,RED12,DARK_LAVENDER0,DARK_LAVENDER4
        .BYTE $07,$00,$00,$00,$00,$00,$00,$00 ; oozeRates
        .BYTE $10,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $03 ; explosionMode
        .BYTE $02 ; unused1
        .BYTE $50 ; unused2
preset26
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $0E ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $06 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $7B ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $00 ; screenMode
        .BYTE $24 ; bufferLength
        .BYTE $02 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK9,DARK_ORANGE1,DARK_ORANGE2,DARK_ORANGE4 ; colorValuesOfSomeSort
        .BYTE DARK_ORANGE6,DARK_ORANGE8,DARK_ORANGE10,DARK_ORANGE12
        .BYTE $00,$00,$00,$00,$00,$00,$00,$00 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $C0 ; unused1
        .BYTE $08 ; unused2
preset27
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $02 ; speedBoostAdjust
        .BYTE $16 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $0B ; pulseSpeed
        .BYTE $02 ; currentPulseWidth
        .BYTE $10 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $01 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,ULTRAMARINE_BLUE0,ULTRAMARINE_BLUE2,ULTRAMARINE_BLUE4 ; colorValuesOfSomeSort
        .BYTE ULTRAMARINE_BLUE6,ULTRAMARINE_BLUE8,ULTRAMARINE_BLUE10,MEDIUM_BLUE0
        .BYTE $00,$00,$00,$00,$00,$00,$00,$02 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $47 ; unused1
        .BYTE $08 ; unused2
preset28
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $04 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $05 ; pulseSpeed
        .BYTE $01 ; currentPulseWidth
        .BYTE $10 ; smoothingDelay
        .BYTE $04 ; currentSymmetry
        .BYTE $00 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE ULTRAMARINE_BLUE0,ULTRAMARINE_BLUE0,ULTRAMARINE_BLUE2,ULTRAMARINE_BLUE4 ; colorValuesOfSomeSort
        .BYTE ULTRAMARINE_BLUE6,ULTRAMARINE_BLUE8,ULTRAMARINE_BLUE10,MEDIUM_BLUE0
        .BYTE $05,$00,$00,$00,$00,$00,$00,$02 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $03 ; explosionMode
        .BYTE $54 ; unused1
        .BYTE $49 ; unused2
preset29
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $02 ; speedBoostAdjust
        .BYTE $04 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $05 ; pulseSpeed
        .BYTE $01 ; currentPulseWidth
        .BYTE $10 ; smoothingDelay
        .BYTE $04 ; currentSymmetry
        .BYTE $00 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $02 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE ULTRAMARINE_BLUE0,ULTRAMARINE_BLUE0,ULTRAMARINE_BLUE2,ULTRAMARINE_BLUE4 ; colorValuesOfSomeSort
        .BYTE ULTRAMARINE_BLUE6,ULTRAMARINE_BLUE8,ULTRAMARINE_BLUE10,MEDIUM_BLUE0
        .BYTE $05,$00,$00,$00,$00,$00,$00,$02 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $04 ; explosionMode
        .BYTE $59 ; unused1
        .BYTE $4D ; unused2
preset30
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $02 ; speedBoostAdjust
        .BYTE $0B ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $02 ; pulseSpeed
        .BYTE $02 ; currentPulseWidth
        .BYTE $09 ; smoothingDelay
        .BYTE $02 ; currentSymmetry
        .BYTE $06 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,ULTRAMARINE_BLUE0,RED3,DARK_ORANGE0 ; colorValuesOfSomeSort
        .BYTE RED_ORANGE6,ORANGE_GREEN12,DARK_GREEN13,DARK_GREEN15
        .BYTE $00,$00,$00,$00,$00,$00,$00,$00 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $0A ; unused1
        .BYTE $60 ; unused2
preset31
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $02 ; speedBoostAdjust
        .BYTE $0B ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $02 ; pulseSpeed
        .BYTE $02 ; currentPulseWidth
        .BYTE $09 ; smoothingDelay
        .BYTE $02 ; currentSymmetry
        .BYTE $05 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,ULTRAMARINE_BLUE0,RED3,DARK_ORANGE0 ; colorValuesOfSomeSort
        .BYTE RED_ORANGE6,ORANGE_GREEN12,DARK_GREEN13,DARK_GREEN15
        .BYTE $00,$00,$00,$00,$00,$00,$00,$00 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $00 ; unused1
        .BYTE $03 ; unused2
preset32
        .BYTE $02 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $05 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $00 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $40 ; smoothingDelay
        .BYTE $02 ; currentSymmetry
        .BYTE $03 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,BLACK2,BLACK14,BLACK4 ; colorValuesOfSomeSort
        .BYTE BLACK12,BLACK6,BLACK10,BLACK8
        .BYTE $00,$05,$05,$05,$05,$05,$05,$05 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $50 ; unused1
        .BYTE $4C ; unused2
preset33
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $06 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $04 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $40 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $06 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,BLACK2,BLACK14,BLACK4 ; colorValuesOfSomeSort
        .BYTE BLACK12,BLACK6,BLACK10,BLACK8
        .BYTE $00,$05,$05,$05,$05,$05,$05,$05 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $59 ; unused1
        .BYTE $0B ; unused2
preset34
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $13 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $01 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $0F ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $02 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,BLACK2,BLACK14,BLACK4 ; colorValuesOfSomeSort
        .BYTE BLACK12,BLACK6,BLACK10,BLACK8
        .BYTE $00,$05,$05,$05,$05,$05,$05,$05 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $00 ; unused1
        .BYTE $8A ; unused2
preset35
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $06 ; speedBoostAdjust
        .BYTE $09 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $04 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $39 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $06 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,DARK_ORANGE1,DARK_ORANGE2,DARK_ORANGE4 ; colorValuesOfSomeSort
        .BYTE DARK_ORANGE6,DARK_ORANGE8,DARK_ORANGE10,DARK_ORANGE12
        .BYTE $00,$03,$03,$03,$03,$03,$03,$03 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $41 ; unused1
        .BYTE $54 ; unused2
preset36
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $06 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $00 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $08 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $02 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,DARK_ORANGE1,DARK_ORANGE2,DARK_ORANGE4 ; colorValuesOfSomeSort
        .BYTE DARK_ORANGE6,DARK_ORANGE8,DARK_ORANGE10,DARK_ORANGE12
        .BYTE $00,$03,$03,$03,$03,$03,$03,$03 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $52 ; unused1
        .BYTE $0A ; unused2
preset37
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $06 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $00 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $10 ; smoothingDelay
        .BYTE $02 ; currentSymmetry
        .BYTE $00 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,RUST2,RUST4,RUST6 ; colorValuesOfSomeSort
        .BYTE RED_ORANGE11,DARK_ORANGE8,MEDIUM_BLUE3,DARK_BLUE8
        .BYTE $00,$00,$00,$00,$00,$00,$00,$00 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $4F ; unused1
        .BYTE $4C ; unused2
preset38
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $09 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $00 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $10 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $01 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,RUST2,RUST4,RUST6 ; colorValuesOfSomeSort
        .BYTE RED_ORANGE11,DARK_ORANGE8,MEDIUM_BLUE3,DARK_BLUE8
        .BYTE $00,$00,$00,$00,$00,$00,$00,$00 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $00 ; unused1
        .BYTE $3F ; unused2
preset39
        .BYTE $02 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $0B ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $00 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $40 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $02 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,RUST2,RUST4,RUST6 ; colorValuesOfSomeSort
        .BYTE RED_ORANGE11,DARK_ORANGE8,MEDIUM_BLUE3,DARK_BLUE8
        .BYTE $00,$02,$02,$02,$02,$00,$00,$00 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $00 ; unused1
        .BYTE $8D ; unused2
preset40
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $10 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $00 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $10 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $03 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK4,RUST8,DARK_ORANGE8,DARK_LAVENDER8 ; colorValuesOfSomeSort
        .BYTE ULTRAMARINE_BLUE8,DARK_BLUE8,OLIVE_GREEN8,DARK_GREEN8
        .BYTE $05,$01,$01,$01,$01,$01,$01,$01 ; oozeRates
        .BYTE $10,$10,$10,$10,$10,$10,$10,$10 ; oozeSteps
        .BYTE $0F,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; oozeCycles
        .BYTE $03 ; explosionMode
        .BYTE $4E ; unused1
        .BYTE $0C ; unused2
preset41
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $02 ; speedBoostAdjust
        .BYTE $01 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $03 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $15 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $02 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,DARK_ORANGE1,DARK_ORANGE2,DARK_ORANGE4 ; colorValuesOfSomeSort
        .BYTE DARK_ORANGE6,COBALT_BLUE8,COBALT_BLUE10,COBALT_BLUE12
        .BYTE $00,$00,$00,$00,$00,$01,$01,$01 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $00 ; unused1
        .BYTE $45 ; unused2
preset42
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $01 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $01 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $15 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $02 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,DARK_ORANGE1,DARK_ORANGE2,DARK_ORANGE4 ; colorValuesOfSomeSort
        .BYTE DARK_ORANGE6,COBALT_BLUE8,COBALT_BLUE10,COBALT_BLUE12
        .BYTE $00,$00,$00,$00,$00,$01,$01,$01 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $00 ; unused1
        .BYTE $06 ; unused2
preset43
        .BYTE $03 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $08 ; speedBoostAdjust
        .BYTE $07 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $01 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $15 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $06 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,DARK_ORANGE1,DARK_ORANGE2,DARK_ORANGE4 ; colorValuesOfSomeSort
        .BYTE DARK_ORANGE6,COBALT_BLUE8,COBALT_BLUE10,COBALT_BLUE12
        .BYTE $00,$00,$00,$00,$00,$01,$01,$01 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $52 ; unused1
        .BYTE $32 ; unused2
preset44
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $0C ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $00 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $08 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $02 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE OLIVE_GREEN0,DARK_ORANGE1,DARK_ORANGE2,DARK_ORANGE4 ; colorValuesOfSomeSort
        .BYTE DARK_ORANGE6,DARK_ORANGE8,DARK_ORANGE10,DARK_ORANGE12
        .BYTE $00,$03,$03,$03,$03,$03,$03,$03 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$12,$13,$14,$15,$16,$17,$18 ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $68 ; unused1
        .BYTE $06 ; unused2
preset45
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $10 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $01 ; pulseSpeed
        .BYTE $02 ; currentPulseWidth
        .BYTE $09 ; smoothingDelay
        .BYTE $02 ; currentSymmetry
        .BYTE $01 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,ULTRAMARINE_BLUE0,RED3,DARK_ORANGE0 ; colorValuesOfSomeSort
        .BYTE RED_ORANGE6,ORANGE_GREEN12,DARK_GREEN13,DARK_GREEN15
        .BYTE $00,$00,$00,$00,$00,$00,$00,$00 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $00 ; unused1
        .BYTE $A3 ; unused2
preset46
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $02 ; speedBoostAdjust
        .BYTE $14 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $04 ; pulseSpeed
        .BYTE $01 ; currentPulseWidth
        .BYTE $04 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $06 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,RUST6,RUST8,RUST10 ; colorValuesOfSomeSort
        .BYTE RUST12,RUST14,RED_ORANGE0,RED_ORANGE2
        .BYTE $00,$02,$02,$02,$02,$02,$02,$02 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $80 ; unused1
        .BYTE $48 ; unused2
preset47
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $14 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $01 ; pulseSpeed
        .BYTE $01 ; currentPulseWidth
        .BYTE $10 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $03 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,ORANGE_GREEN6,ORANGE_GREEN8,ORANGE_GREEN10 ; colorValuesOfSomeSort
        .BYTE ORANGE_GREEN12,ORANGE_GREEN14,ORANGE0,ORANGE2
        .BYTE $00,$02,$02,$02,$02,$02,$02,$02 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $00 ; unused1
        .BYTE $F7 ; unused2
preset48
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $15 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $01 ; pulseSpeed
        .BYTE $01 ; currentPulseWidth
        .BYTE $10 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $06 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,ORANGE_GREEN6,ORANGE_GREEN8,ORANGE_GREEN10 ; colorValuesOfSomeSort
        .BYTE ORANGE_GREEN12,ORANGE_GREEN14,ORANGE0,ORANGE2
        .BYTE $00,$02,$02,$02,$02,$02,$02,$02 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $44 ; unused1
        .BYTE $44 ; unused2
preset49
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $08 ; currentPatternIndex
        .BYTE $02 ; verticalResolutionSPAC
        .BYTE $01 ; pulseSpeed
        .BYTE $01 ; currentPulseWidth
        .BYTE $10 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $00 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,ORANGE_GREEN6,ORANGE_GREEN8,ORANGE_GREEN10 ; colorValuesOfSomeSort
        .BYTE ORANGE_GREEN12,ORANGE_GREEN14,ORANGE0,ORANGE2
        .BYTE $00,$02,$02,$02,$02,$02,$02,$02 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $07 ; unused1
        .BYTE $44 ; unused2
preset50
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $10 ; currentPatternIndex
        .BYTE $02 ; verticalResolutionSPAC
        .BYTE $01 ; pulseSpeed
        .BYTE $01 ; currentPulseWidth
        .BYTE $0C ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $01 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,COBALT_BLUE6,COBALT_BLUE8,COBALT_BLUE10 ; colorValuesOfSomeSort
        .BYTE COBALT_BLUE12,COBALT_BLUE14,ULTRAMARINE_BLUE0,ULTRAMARINE_BLUE2
        .BYTE $00,$02,$02,$02,$02,$02,$02,$02 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $00 ; unused1
        .BYTE $8A ; unused2
preset51
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $13 ; currentPatternIndex
        .BYTE $02 ; verticalResolutionSPAC
        .BYTE $01 ; pulseSpeed
        .BYTE $01 ; currentPulseWidth
        .BYTE $0C ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $02 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,ORANGE_GREEN6,ORANGE_GREEN8,ORANGE_GREEN10 ; colorValuesOfSomeSort
        .BYTE ORANGE_GREEN12,ORANGE_GREEN14,ORANGE0,ORANGE2
        .BYTE $00,$02,$02,$02,$02,$02,$02,$02 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$40,$40,$20,$20,$40,$20,$40 ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $35 ; unused1
        .BYTE $09 ; unused2
preset52
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $16 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $02 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $10 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $03 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,ULTRAMARINE_BLUE0,ULTRAMARINE_BLUE2,ULTRAMARINE_BLUE4 ; colorValuesOfSomeSort
        .BYTE ULTRAMARINE_BLUE6,ULTRAMARINE_BLUE8,ULTRAMARINE_BLUE10,MEDIUM_BLUE0
        .BYTE $00,$00,$00,$00,$00,$00,$00,$00 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $00 ; unused1
        .BYTE $3E ; unused2
preset53
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $02 ; speedBoostAdjust
        .BYTE $01 ; currentPatternIndex
        .BYTE $02 ; verticalResolutionSPAC
        .BYTE $02 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $0A ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $00 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE DARK_BLUE0,ULTRAMARINE_BLUE14,ULTRAMARINE_BLUE14,ULTRAMARINE_BLUE12 ; colorValuesOfSomeSort
        .BYTE ULTRAMARINE_BLUE10,ULTRAMARINE_BLUE8,ULTRAMARINE_BLUE6,ULTRAMARINE_BLUE4
        .BYTE $00,$00,$00,$00,$00,$00,$00,$00 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $00 ; unused1
        .BYTE $4A ; unused2
preset54
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $02 ; speedBoostAdjust
        .BYTE $01 ; currentPatternIndex
        .BYTE $02 ; verticalResolutionSPAC
        .BYTE $02 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $0A ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $00 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE DARK_BLUE0,ULTRAMARINE_BLUE14,ULTRAMARINE_BLUE14,ULTRAMARINE_BLUE12 ; colorValuesOfSomeSort
        .BYTE ULTRAMARINE_BLUE10,ULTRAMARINE_BLUE8,ULTRAMARINE_BLUE6,ULTRAMARINE_BLUE4
        .BYTE $00,$02,$02,$02,$02,$02,$02,$02 ; oozeRates
        .BYTE $01,$10,$10,$10,$10,$10,$10,$10 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $52 ; unused1
        .BYTE $45 ; unused2
preset55
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $01 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $00 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $10 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $00 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,ULTRAMARINE_BLUE4,COBALT_BLUE6,COBALT_BLUE10 ; colorValuesOfSomeSort
        .BYTE MEDIUM_BLUE15,COBALT_BLUE5,DARK_BLUE1,DARK_BLUE17
        .BYTE $00,$00,$00,$00,$00,$00,$00,$00 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $04 ; unused1
        .BYTE $FF ; unused2
preset56
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $0B ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $01 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $10 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $03 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK4,ULTRAMARINE_BLUE6,ULTRAMARINE_BLUE6,ULTRAMARINE_BLUE6 ; colorValuesOfSomeSort
        .BYTE ULTRAMARINE_BLUE6,ULTRAMARINE_BLUE6,ULTRAMARINE_BLUE6,ULTRAMARINE_BLUE6
        .BYTE $20,$02,$02,$02,$02,$02,$02,$02 ; oozeRates
        .BYTE $10,$01,$02,$03,$04,$05,$06,$07 ; oozeSteps
        .BYTE $0F,$20,$20,$20,$20,$20,$20,$20 ; oozeCycles
        .BYTE $07 ; explosionMode
        .BYTE $43 ; unused1
        .BYTE $4F ; unused2
preset57
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $10 ; currentPatternIndex
        .BYTE $02 ; verticalResolutionSPAC
        .BYTE $01 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $10 ; smoothingDelay
        .BYTE $02 ; currentSymmetry
        .BYTE $06 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,ULTRAMARINE_BLUE6,ULTRAMARINE_BLUE6,ULTRAMARINE_BLUE6 ; colorValuesOfSomeSort
        .BYTE ULTRAMARINE_BLUE6,ULTRAMARINE_BLUE6,ULTRAMARINE_BLUE6,ULTRAMARINE_BLUE6
        .BYTE $00,$02,$02,$02,$02,$02,$02,$02 ; oozeRates
        .BYTE $10,$01,$02,$03,$04,$05,$06,$07 ; oozeSteps
        .BYTE $0F,$20,$20,$20,$20,$20,$20,$20 ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $00 ; unused1
        .BYTE $D9 ; unused2
preset58
        .BYTE $02 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $15 ; currentPatternIndex
        .BYTE $04 ; verticalResolutionSPAC
        .BYTE $00 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $10 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $00 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,OLIVE_GREEN4,OLIVE_GREEN6,OLIVE_GREEN8 ; colorValuesOfSomeSort
        .BYTE OLIVE_GREEN10,OLIVE_GREEN12,OLIVE_GREEN10,OLIVE_GREEN8
        .BYTE $00,$01,$01,$01,$01,$01,$01,$01 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $0A ; unused1
        .BYTE $D6 ; unused2
preset59
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $10 ; currentPatternIndex
        .BYTE $02 ; verticalResolutionSPAC
        .BYTE $00 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $10 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $01 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,OLIVE_GREEN4,OLIVE_GREEN6,OLIVE_GREEN8 ; colorValuesOfSomeSort
        .BYTE OLIVE_GREEN10,OLIVE_GREEN12,OLIVE_GREEN10,OLIVE_GREEN8
        .BYTE $00,$01,$01,$01,$01,$01,$01,$01 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$2E,$2E,$2E,$2E,$2E,$2E,$2E ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $45 ; unused1
        .BYTE $58 ; unused2
preset60
        .BYTE $02 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $03 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $01 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $15 ; smoothingDelay
        .BYTE $02 ; currentSymmetry
        .BYTE $02 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,DARK_ORANGE1,DARK_ORANGE2,DARK_ORANGE4 ; colorValuesOfSomeSort
        .BYTE DARK_ORANGE6,COBALT_BLUE8,COBALT_BLUE10,COBALT_BLUE12
        .BYTE $00,$01,$01,$01,$01,$00,$00,$00 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $33 ; unused1
        .BYTE $41 ; unused2
preset61
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $02 ; speedBoostAdjust
        .BYTE $09 ; currentPatternIndex
        .BYTE $02 ; verticalResolutionSPAC
        .BYTE $02 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $08 ; smoothingDelay
        .BYTE $02 ; currentSymmetry
        .BYTE $00 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,DARK_ORANGE1,DARK_ORANGE2,DARK_ORANGE4 ; colorValuesOfSomeSort
        .BYTE DARK_ORANGE6,DARK_ORANGE8,DARK_ORANGE10,DARK_ORANGE12
        .BYTE $00,$03,$03,$03,$03,$03,$03,$03 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$40,$40,$40,$40,$40,$40,$40 ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $4C ; unused1
        .BYTE $C0 ; unused2
preset62
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $02 ; speedBoostAdjust
        .BYTE $14 ; currentPatternIndex
        .BYTE $02 ; verticalResolutionSPAC
        .BYTE $02 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $08 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $04 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,DARK_ORANGE1,DARK_ORANGE2,DARK_ORANGE4 ; colorValuesOfSomeSort
        .BYTE DARK_ORANGE6,DARK_ORANGE8,DARK_ORANGE10,DARK_ORANGE12
        .BYTE $00,$03,$03,$03,$03,$03,$03,$03 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$40,$40,$40,$41,$40,$40,$40 ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $09 ; unused1
        .BYTE $70 ; unused2
preset63
        .BYTE $02 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $09 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $00 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $6B ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $02 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,RUST8,DARK_ORANGE8,DARK_LAVENDER8 ; colorValuesOfSomeSort
        .BYTE ULTRAMARINE_BLUE8,DARK_BLUE8,OLIVE_GREEN8,DARK_GREEN8
        .BYTE $00,$03,$03,$03,$03,$03,$03,$03 ; oozeRates
        .BYTE $01,$10,$10,$10,$10,$10,$10,$10 ; oozeSteps
        .BYTE $0F,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $45 ; unused1
        .BYTE $59 ; unused2
preset64
        .BYTE $04 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $04 ; speedBoostAdjust
        .BYTE $01 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $00 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $08 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $03 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,BLACK2,BLACK14,BLACK4 ; colorValuesOfSomeSort
        .BYTE BLACK12,BLACK6,BLACK10,BLACK8
        .BYTE $00,$02,$02,$02,$02,$02,$02,$02 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $48 ; unused1
        .BYTE $4F ; unused2
preset65
        .BYTE $04 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $04 ; speedBoostAdjust
        .BYTE $01 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $00 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $08 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $03 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $02 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK7,BLACK2,BLACK14,BLACK4 ; colorValuesOfSomeSort
        .BYTE BLACK12,BLACK6,BLACK10,BLACK8
        .BYTE $00,$00,$00,$00,$00,$00,$00,$00 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $5A ; unused1
        .BYTE $0A ; unused2
preset66
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $13 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $00 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $08 ; smoothingDelay
        .BYTE $02 ; currentSymmetry
        .BYTE $06 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,DARK_ORANGE1,DARK_ORANGE2,DARK_ORANGE4 ; colorValuesOfSomeSort
        .BYTE DARK_ORANGE6,DARK_ORANGE8,DARK_ORANGE10,DARK_ORANGE12
        .BYTE $00,$03,$03,$03,$03,$03,$03,$03 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $53 ; unused1
        .BYTE $30 ; unused2
preset67
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $11 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $00 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $10 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $00 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,OLIVE_GREEN4,OLIVE_GREEN6,OLIVE_GREEN8 ; colorValuesOfSomeSort
        .BYTE OLIVE_GREEN10,OLIVE_GREEN12,OLIVE_GREEN10,OLIVE_GREEN8
        .BYTE $00,$01,$01,$01,$01,$01,$01,$01 ; oozeRates
        .BYTE $01,$02,$02,$03,$03,$05,$05,$06 ; oozeSteps
        .BYTE $0F,$20,$20,$20,$20,$20,$20,$20 ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $32 ; unused1
        .BYTE $0A ; unused2
preset68
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $02 ; speedBoostAdjust
        .BYTE $14 ; currentPatternIndex
        .BYTE $02 ; verticalResolutionSPAC
        .BYTE $02 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $05 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $00 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK4,RUST8,DARK_ORANGE8,DARK_LAVENDER8 ; colorValuesOfSomeSort
        .BYTE ULTRAMARINE_BLUE8,DARK_BLUE8,OLIVE_GREEN8,DARK_GREEN8
        .BYTE $05,$01,$01,$01,$01,$01,$01,$01 ; oozeRates
        .BYTE $10,$10,$10,$10,$10,$10,$10,$10 ; oozeSteps
        .BYTE $0F,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; oozeCycles
        .BYTE $02 ; explosionMode
        .BYTE $0A ; unused1
        .BYTE $4D ; unused2
preset69
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $10 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $00 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $08 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $02 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,DARK_ORANGE1,DARK_ORANGE2,DARK_ORANGE4 ; colorValuesOfSomeSort
        .BYTE DARK_ORANGE6,DARK_ORANGE8,DARK_ORANGE10,DARK_ORANGE12
        .BYTE $00,$03,$03,$03,$03,$03,$03,$03 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $0A ; unused1
        .BYTE $A1 ; unused2
preset70
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $11 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $00 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $08 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $02 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,DARK_ORANGE1,DARK_ORANGE2,DARK_ORANGE4 ; colorValuesOfSomeSort
        .BYTE DARK_ORANGE6,DARK_ORANGE8,DARK_ORANGE10,DARK_ORANGE12
        .BYTE $00,$03,$03,$03,$03,$03,$03,$03 ; oozeRates
        .BYTE $01,$08,$08,$08,$08,$08,$08,$08 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $45 ; unused1
        .BYTE $4E ; unused2
preset71
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $02 ; speedBoostAdjust
        .BYTE $07 ; currentPatternIndex
        .BYTE $06 ; verticalResolutionSPAC
        .BYTE $02 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $05 ; smoothingDelay
        .BYTE $04 ; currentSymmetry
        .BYTE $01 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,RUST8,DARK_ORANGE8,DARK_LAVENDER8 ; colorValuesOfSomeSort
        .BYTE ULTRAMARINE_BLUE8,DARK_BLUE8,OLIVE_GREEN8,DARK_GREEN8
        .BYTE $00,$01,$01,$01,$01,$01,$01,$01 ; oozeRates
        .BYTE $10,$10,$10,$10,$10,$10,$10,$10 ; oozeSteps
        .BYTE $0F,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $45 ; unused1
        .BYTE $0B ; unused2
preset72
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $09 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $02 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $10 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $03 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,DARK_ORANGE1,DARK_ORANGE2,DARK_ORANGE4 ; colorValuesOfSomeSort
        .BYTE DARK_ORANGE6,DARK_ORANGE8,DARK_ORANGE10,DARK_ORANGE12
        .BYTE $00,$00,$00,$00,$00,$00,$00,$00 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $0B ; unused1
        .BYTE $4B ; unused2
preset73
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $0B ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $01 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $10 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $06 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,DARK_ORANGE1,DARK_ORANGE2,DARK_ORANGE4 ; colorValuesOfSomeSort
        .BYTE DARK_ORANGE6,DARK_ORANGE8,DARK_ORANGE10,DARK_ORANGE12
        .BYTE $00,$14,$14,$14,$14,$14,$14,$14 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$00,$00,$00,$00,$00,$00,$00 ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $0C ; unused1
        .BYTE $4B ; unused2
preset74
        .BYTE $02 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $0B ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $01 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $10 ; smoothingDelay
        .BYTE $04 ; currentSymmetry
        .BYTE $00 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,DARK_ORANGE1,DARK_ORANGE2,DARK_ORANGE4 ; colorValuesOfSomeSort
        .BYTE DARK_ORANGE6,DARK_ORANGE8,DARK_ORANGE10,DARK_ORANGE12
        .BYTE $00,$14,$14,$14,$14,$14,$14,$14 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$00,$00,$00,$00,$00,$00,$00 ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $09 ; unused1
        .BYTE $C4 ; unused2
preset75
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $02 ; speedBoostAdjust
        .BYTE $11 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $02 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $10 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $02 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,DARK_ORANGE1,DARK_ORANGE2,DARK_ORANGE4 ; colorValuesOfSomeSort
        .BYTE DARK_ORANGE6,DARK_ORANGE8,DARK_ORANGE10,DARK_ORANGE12
        .BYTE $00,$14,$14,$14,$14,$14,$14,$14 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$00,$00,$00,$00,$00,$00,$00 ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $44 ; unused1
        .BYTE $4F ; unused2
preset76
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $02 ; speedBoostAdjust
        .BYTE $01 ; currentPatternIndex
        .BYTE $02 ; verticalResolutionSPAC
        .BYTE $04 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $06 ; smoothingDelay
        .BYTE $04 ; currentSymmetry
        .BYTE $00 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $01 ; stroboscopicsEnabled
        .BYTE $01 ; stroboFlashRate
        .BYTE BLACK5,DARK_ORANGE1,DARK_ORANGE2,DARK_ORANGE4 ; colorValuesOfSomeSort
        .BYTE DARK_ORANGE6,DARK_ORANGE8,DARK_ORANGE10,DARK_ORANGE12
        .BYTE $00,$14,$14,$14,$14,$14,$14,$14 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$00,$00,$00,$00,$00,$00,$00 ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $80 ; unused1
        .BYTE $69 ; unused2
preset77
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $06 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $00 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $08 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $02 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,DARK_ORANGE1,DARK_ORANGE2,DARK_ORANGE4 ; colorValuesOfSomeSort
        .BYTE DARK_ORANGE6,DARK_ORANGE8,DARK_ORANGE10,DARK_ORANGE12
        .BYTE $00,$03,$03,$03,$03,$03,$03,$03 ; oozeRates
        .BYTE $01,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $00 ; unused1
        .BYTE $0C ; unused2
preset78
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $09 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $00 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $08 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $03 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $02 ; stroboFlashRate
        .BYTE BLACK0,DARK_ORANGE1,DARK_ORANGE2,DARK_ORANGE4 ; colorValuesOfSomeSort
        .BYTE DARK_ORANGE6,DARK_ORANGE8,DARK_ORANGE10,DARK_ORANGE12
        .BYTE $01,$03,$03,$03,$03,$03,$03,$03 ; oozeRates
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $01 ; explosionMode
        .BYTE $0C ; unused1
        .BYTE $4B ; unused2
preset79
        .BYTE $01 ; cursorSpeed
        .BYTE $01 ; vectorMode
        .BYTE $01 ; speedBoostAdjust
        .BYTE $13 ; currentPatternIndex
        .BYTE $05 ; verticalResolutionSPAC
        .BYTE $01 ; pulseSpeed
        .BYTE $00 ; currentPulseWidth
        .BYTE $08 ; smoothingDelay
        .BYTE $01 ; currentSymmetry
        .BYTE $02 ; screenMode
        .BYTE $40 ; bufferLength
        .BYTE $00 ; stroboscopicsEnabled
        .BYTE $05 ; stroboFlashRate
        .BYTE DARK_ORANGE13,DARK_ORANGE1,DARK_ORANGE2,DARK_ORANGE4 ; colorValuesOfSomeSort
        .BYTE DARK_ORANGE6,DARK_ORANGE8,DARK_ORANGE10,DARK_ORANGE12
        .BYTE $00,$00,$00,$00,$00,$00,$00,$00 ; oozeRates
        .BYTE $01,$01,$01,$01,$01,$01,$01,$01 ; oozeSteps
        .BYTE $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F ; oozeCycles
        .BYTE $00 ; explosionMode
        .BYTE $06 ; unused1
        .BYTE $00 ; unused2
preset80
        .BYTE $7E ; cursorSpeed
        .BYTE $18 ; vectorMode
        .BYTE $10 ; speedBoostAdjust
        .BYTE $83 ; currentPatternIndex
        .BYTE $47 ; verticalResolutionSPAC
        .BYTE $47 ; pulseSpeed
        .BYTE $49 ; currentPulseWidth
        .BYTE $51 ; smoothingDelay
        .BYTE $86 ; currentSymmetry
        .BYTE $53 ; screenMode
        .BYTE $50 ; bufferLength
        .BYTE $41 ; stroboscopicsEnabled
        .BYTE $52 ; stroboFlashRate
        .BYTE RED5,RED3,DARK_ORANGE9,MEDIUM_BLUE8 ; colorValuesOfSomeSort
        .BYTE RUST8,BLACK12,DARK_LAVENDER0,MEDIUM_BLUE6
        .BYTE $43,$4F,$4C,$4F,$52,$53,$39,$92 ; oozeRates
        .BYTE $18,$0A,$51,$84,$46,$52,$45,$51 ; oozeSteps
        .BYTE $39,$9C,$18,$0B,$50,$85,$46,$52 ; oozeCycles
        .BYTE $45 ; explosionMode
        .BYTE $51 ; unused1
        .BYTE $52 ; unused2
preset81
        .BYTE $39 ; cursorSpeed
        .BYTE $A6 ; vectorMode
        .BYTE $18 ; speedBoostAdjust
        .BYTE $0B ; currentPatternIndex
        .BYTE $51 ; verticalResolutionSPAC
        .BYTE $85 ; pulseSpeed
        .BYTE $43 ; currentPulseWidth
        .BYTE $59 ; smoothingDelay
        .BYTE $43 ; currentSymmetry
        .BYTE $4C ; screenMode
        .BYTE $45 ; bufferLength
        .BYTE $39 ; stroboscopicsEnabled
        .BYTE $B0 ; stroboFlashRate
        .BYTE RUST8,BLACK10,DARK_LAVENDER0,MEDIUM_BLUE4 ; colorValuesOfSomeSort
        .BYTE RED3,DARK_LAVENDER9,RED3,DARK_LAVENDER2
        .BYTE $39,$BA,$18,$04,$32,$C4,$18,$07 ; oozeRates
        .BYTE $28,$3E,$06,$08,$CE,$18,$08,$48 ; oozeSteps
        .BYTE $83,$47,$47,$49,$D8,$18,$0E,$51 ; oozeCycles
        .BYTE $86 ; explosionMode
        .BYTE $53 ; unused1
        .BYTE $50 ; unused2
preset82
        .BYTE $41 ; cursorSpeed
        .BYTE $52 ; vectorMode
        .BYTE $45 ; speedBoostAdjust
        .BYTE $43 ; currentPatternIndex
        .BYTE $12 ; verticalResolutionSPAC
        .BYTE $08 ; pulseSpeed
        .BYTE $08 ; currentPulseWidth
        .BYTE $E2 ; smoothingDelay
        .BYTE $18 ; currentSymmetry
        .BYTE $0E ; screenMode
        .BYTE $50 ; bufferLength
        .BYTE $86 ; stroboscopicsEnabled
        .BYTE $43 ; stroboFlashRate
        .BYTE RED15,RED12,RED15,DARK_LAVENDER2 ; colorValuesOfSomeSort
        .BYTE DARK_LAVENDER3,RUST2,BLACK8,BLACK8
        .BYTE $E3,$18,$07,$51,$3E,$06,$01,$E4 ; oozeRates
        .BYTE $18,$0B,$50,$86,$43,$48,$4C,$49 ; oozeSteps
        .BYTE $53,$54,$EC,$18,$08,$21,$83,$42 ; oozeCycles
        .BYTE $48 ; explosionMode
        .BYTE $41 ; unused1
        .BYTE $F6 ; unused2
preset83
        .BYTE $18 ; cursorSpeed
        .BYTE $10 ; vectorMode
        .BYTE $84 ; speedBoostAdjust
        .BYTE $47 ; currentPatternIndex
        .BYTE $49 ; verticalResolutionSPAC
        .BYTE $4E ; pulseSpeed
        .BYTE $43 ; currentPulseWidth
        .BYTE $51 ; smoothingDelay
        .BYTE $40 ; currentSymmetry
        .BYTE $84 ; screenMode
        .BYTE $49 ; bufferLength
        .BYTE $58 ; stroboscopicsEnabled
        .BYTE $4C ; stroboFlashRate
        .BYTE RED15,DARK_ORANGE7,BLACK0,RUST9 ; colorValuesOfSomeSort
        .BYTE BLACK4,DARK_ORANGE3,BLACK10,RUST9
        .BYTE $04,$3A,$14,$19,$0A,$85,$4B,$45 ; oozeRates
        .BYTE $59,$31,$38,$35,$1E,$19,$07,$4D ; oozeSteps
        .BYTE $3E,$06,$3F,$28,$19,$07,$52,$3E ; oozeCycles
        .BYTE $06 ; explosionMode
        .BYTE $08 ; unused1
        .BYTE $32 ; unused2
preset84
        .BYTE $19 ; cursorSpeed
        .BYTE $07 ; vectorMode
        .BYTE $46 ; speedBoostAdjust
        .BYTE $82 ; currentPatternIndex
        .BYTE $4B ; verticalResolutionSPAC
        .BYTE $5A ; pulseSpeed
        .BYTE $3C ; currentPulseWidth
        .BYTE $19 ; smoothingDelay
        .BYTE $04 ; currentSymmetry
        .BYTE $37 ; screenMode
        .BYTE $46 ; bufferLength
        .BYTE $19 ; stroboscopicsEnabled
        .BYTE $0A ; stroboFlashRate
        .BYTE RED_ORANGE1,MEDIUM_BLUE5,RED11,RED5 ; colorValuesOfSomeSort
        .BYTE DARK_LAVENDER9,DARK_ORANGE1,DARK_ORANGE9,DARK_LAVENDER0
        .BYTE $19,$07,$82,$4B,$5A,$37,$5A,$19 ; oozeRates
        .BYTE $07,$4D,$3E,$06,$C0,$64,$19,$09 ; oozeSteps
        .BYTE $48,$84,$4E,$4F,$4B,$4F,$6E,$19 ; oozeCycles
        .BYTE $04 ; explosionMode
        .BYTE $3A ; unused1
        .BYTE $78 ; unused2
preset85
        .BYTE $19 ; cursorSpeed
        .BYTE $0C ; vectorMode
        .BYTE $84 ; speedBoostAdjust
        .BYTE $4E ; currentPatternIndex
        .BYTE $4F ; verticalResolutionSPAC
        .BYTE $4B ; pulseSpeed
        .BYTE $4F ; currentPulseWidth
        .BYTE $52 ; smoothingDelay
        .BYTE $3E ; currentSymmetry
        .BYTE $06 ; screenMode
        .BYTE $80 ; bufferLength
        .BYTE $82 ; stroboscopicsEnabled
        .BYTE $19 ; stroboFlashRate
        .BYTE BLACK9,RED6,MEDIUM_BLUE4 ; colorValuesOfSomeSort

