name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v3
      with:
        repository: irmen/64tass
        

    - name: Install dependencies
      run: |
        cd 64tass
        make

    - uses: actions/checkout@v3

    - name: Build Psychedelia
      run: make psychedelia.prg

